language: go
dist: bionic
arch:
  - amd64
  - arm64
go:
  - 1.17.x
  - 1.16.x
  - 1.15.x
  - 1.14.x
  - 1.13.x
install:
  - go mod vendor
script:
  - go test -v ./sm2/... --bench=. -cover
  - go test -v ./sm3/... --bench=. -cover
  - go test -v ./sm4/... --bench=. -cover
  - go test -v ./utils/... --bench=. -cover
  - go test -v ./internal/... --bench=. -cover
