name: Go

on: [push, pull_request]

jobs:

  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-latest, self-hosted]
    runs-on:  ${{ matrix.os }}
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: go mod vendor
    - name: TestSm2
      run: go test -v ./sm2/

    - name: TestSm3
      run: go test -v ./sm3/

    - name: TestSm4
      run: go test -v ./sm4/
